{
 "title": "Mini Project 2 Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature of Testbed grenoble",
   "type": "timeseries",
   "description": "Temperature of Testbed sensor Grenoble",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "temperature",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "grenoble",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "place::tag", "operator": "=", "value": "grenoble" }
     ]
    }
   ]
  },
  {
   "title": "Temperature of Testbed strasbourg",
   "type": "timeseries",
   "description": "Temperature of Testbed sensor",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "temperature",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "strasbourg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "place::tag", "operator": "=", "value": "strasbourg" }
     ]
    }
   ]
  },
  {
   "title": "Temperature of Testbed lille",
   "type": "timeseries",
   "description": "Temperature of Testbed sensor lille",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "temperature",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "lille",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "place::tag", "operator": "=", "value": "lille" }
     ]
    }
   ]
  },
  {
   "title": "Temperature of Testbed saclay",
   "type": "timeseries",
   "description": "Temperature of Testbed sensor saclay",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "temperature",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "saclay",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "place::tag", "operator": "=", "value": "saclay" }
     ]
    }
   ]
  }
 ]
}